[package]
authors = ["Adrian Sieber <@ad-si>"]
categories = ["office"]
description = "Generate beautiful invoices from a simple data record."
disciplines = ["business"]
entrypoint = "invoice-maker.typ"
exclude = ["*.pdf", "fixtures", "images", "typescript_pandoc"]
keywords = ["invoice", "accounting", "finance", "money"]
license = "ISC"
name = "invoice-maker"
repository = "https://github.com/ad-si/invoice-maker"
version = "1.0.0"

[template]
entrypoint = "main.typ"
path = "template"
thumbnail = "images/example-invoice-hq.png"
