name: Run tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Typst
        run: cargo install typst-cli

      - name: Install Ghostscript
        run: sudo apt-get install ghostscript

      - name: Install ImageMagick
        uses: mfinelli/setup-imagemagick@v5

      - name: Run tests
        run: make test

      - name: Upload PDFs and PDF diffs
        uses: actions/upload-artifact@v4
        with:
          name: pdf-diffs
          path: |
            examples/*.pdf
            template/*.pdf
            diff_*.png
